cookies = {
    'COMPASS': '',
    'SID': '',
    '__Secure-1PSID': '',
    '__Secure-3PSID': '',
    'HSID': '',
    'SSID': '',
    'APISID': '',
    'SAPISID': '',
    '__Secure-1PAPISID': '',
    '__Secure-3PAPISID': '',
    'OSID': '.',
    '__Secure-OSID': '.',
    'OTZ': '',
    'AEC': '',
    '1P_JAR': '2',
    'DRIVE_STREAM': '',
    'NID': '',
    'SIDCC': '',
    '__Secure-1PSIDCC': '',
    '__Secure-3PSIDCC': '',
}

headers = {
    'authority': '',
    'accept': '',
    'accept-language': '',
    'cache-control': '',
    # 'cookie': '',
    'sec-ch-ua': '',
    'sec-ch-ua-arch': '',
    'sec-ch-ua-bitness': '',
    'sec-ch-ua-full-version': '',
    'sec-ch-ua-full-version-list': '',
    'sec-ch-ua-mobile': '',
    'sec-ch-ua-model': '',
    'sec-ch-ua-platform': '',
    'sec-ch-ua-platform-version': '',
    'sec-ch-ua-wow64': '',
    'sec-fetch-dest': '',
    'sec-fetch-mode': '',
    'sec-fetch-site': '',
    'sec-fetch-user': '',
    'upgrade-insecure-requests': '',
    'user-agent': '',
    'x-chrome-connected': '',
    'x-client-data': '',
}
